/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WWMacYJU5UL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function shad() {
  return (
    <div className="min-h-screen w-full">
      <header className="bg-amazon-yellow py-4 px-6 md:px-12 lg:px-20 shadow-md">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2 font-bold text-2xl" prefetch={false}>
            <AppleIcon className="h-8 w-8" />
            <span>Amazon</span>
          </Link>
          <div className="flex items-center gap-4">
            <div className="relative">
              <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500" />
              <Input
                type="search"
                placeholder="Search Amazon"
                className="rounded-md bg-white px-10 py-2 focus:outline-none"
              />
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="rounded-full">
                  <img
                    src="/placeholder.svg"
                    width="32"
                    height="32"
                    className="rounded-full"
                    alt="Avatar"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }}
                  />
                  <span className="sr-only">Toggle user menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Profile</DropdownMenuItem>
                <DropdownMenuItem>Orders</DropdownMenuItem>
                <DropdownMenuItem>Recommendations</DropdownMenuItem>
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Sign Out</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <div className="grid min-h-[calc(100vh-80px)] w-full overflow-hidden lg:grid-cols-[280px_1fr]">
        <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
          <div className="flex h-full max-h-screen flex-col gap-2">
            <div className="flex h-[60px] items-center border-b px-6">
              <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
                <AppleIcon className="h-6 w-6" />
                <span className="">Amazon</span>
              </Link>
            </div>
            <div className="flex-1 overflow-auto py-2">
              <nav className="grid items-start px-4 text-sm font-medium">
                <Link
                  href="#"
                  className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  prefetch={false}
                >
                  <ShoppingCartIcon className="h-4 w-4" />
                  Orders
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  prefetch={false}
                >
                  <ThumbsUpIcon className="h-4 w-4" />
                  Recommendations
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  prefetch={false}
                >
                  <UserIcon className="h-4 w-4" />
                  Account
                </Link>
              </nav>
            </div>
          </div>
        </div>
        <div className="flex flex-col">
          <main className="flex-1 overflow-auto">
            <div className="grid gap-6 p-4 md:p-6 lg:p-8">
              <section>
                <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-bold">Featured Products</h2>
                  <Link href="#" className="text-amazon-yellow font-medium" prefetch={false}>
                    View All
                  </Link>
                </div>
                <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Echo Dot (4th Gen)</h3>
                      <h4 className="font-semibold">$49.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Fire TV Stick 4K</h3>
                      <h4 className="font-semibold">$49.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Kindle Paperwhite</h3>
                      <h4 className="font-semibold">$129.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Instant Pot Duo</h3>
                      <h4 className="font-semibold">$79.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Bose Noise Cancelling Headphones</h3>
                      <h4 className="font-semibold">$299.99</h4>
                    </div>
                  </div>
                </div>
              </section>
              <section>
                <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-bold">Recommended for You</h2>
                  <Link href="#" className="text-amazon-yellow font-medium" prefetch={false}>
                    View All
                  </Link>
                </div>
                <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Bose Noise Cancelling Headphones</h3>
                      <h4 className="font-semibold">$299.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Kindle Paperwhite</h3>
                      <h4 className="font-semibold">$129.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Fire TV Stick 4K</h3>
                      <h4 className="font-semibold">$49.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Echo Dot (4th Gen)</h3>
                      <h4 className="font-semibold">$49.99</h4>
                    </div>
                  </div>
                  <div className="relative group">
                    <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                      <span className="sr-only">View</span>
                    </Link>
                    <img
                      src="/placeholder.svg"
                      alt="Product Image"
                      width={200}
                      height={200}
                      className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                    />
                    <div className="flex-1 py-2">
                      <h3 className="font-semibold tracking-tight">Instant Pot Duo</h3>
                      <h4 className="font-semibold">$79.99</h4>
                    </div>
                  </div>
                </div>
              </section>
              <section>
                <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-bold">Recent Orders</h2>
                  <Link href="#" className="text-amazon-yellow font-medium" prefetch={false}>
                    View All
                  </Link>
                </div>
                <div className="mt-4">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead className="w-[100px]">Order</TableHead>
                        <TableHead className="min-w-[150px]">Item</TableHead>
                        <TableHead className="text-right">Amount</TableHead>
                        <TableHead className="text-right">Status</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">#3210</TableCell>
                        <TableCell>Wireless Headphones</TableCell>
                        <TableCell className="text-right">$42.25</TableCell>
                        <TableCell className="text-right">Delivered</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">#3209</TableCell>
                        <TableCell>Instant Pot</TableCell>
                        <TableCell className="text-right">$74.99</TableCell>
                        <TableCell className="text-right">Shipped</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">#3204</TableCell>
                        <TableCell>Kindle Paperwhite</TableCell>
                        <TableCell className="text-right">$64.75</TableCell>
                        <TableCell className="text-right">Pending</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </section>
              <section>
                <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-bold">Account Details</h2>
                  <Link href="#" className="text-amazon-yellow font-medium" prefetch={false}>
                    View Profile
                  </Link>
                </div>
                <div className="mt-4 grid gap-2">
                  <div className="flex items-center justify-between">
                    <span>Name:</span>
                    <span className="font-medium">John Doe</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span />
                  </div>
                </div>
              </section>
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}

function AppleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
